#ifndef CONSTANTS_H
#define CONSTANTS_H
// Global Constants
#define BASE_GHOST_SCORE 200
#define CHASE_TIME_LIMIT 20.0f
#define DOT_PELLET_SCORE_VALUE 1
#define FRAMERATE_DELAY 16
#define FRIGHTEN_GHOST_MODE_DURATION 6.0f
#define GAME_FPS 60
#define GHOST_HOUSE_ENTRANCE_COLUMN 13
#define GHOST_HOUSE_ENTRANCE_ROW 11
#define GHOST_SPEED 6.0f
#define GHOST_SPEED_EYES 12.0f
#define GHOST_SPEED_FRIGHTENED 5.0f
#define GHOST_COUNT 4
#define NUMBER_OF_DOTS 244
#define PATH_TO_MAZE_FILE "./assets/maze.txt"
#define PLAYER_LIVES 3
#define PLAYER_SPEED 7.0f
#define POWER_PELLET_SCORE_VALUE 50
#define SCATTER_TIME_LIMIT 7.0f
#define SCREEN_HEIGHT 480
#define SCREEN_WIDTH 640
#define RELEASE_THRESHOLD_PINKY 0
#define RELEASE_THRESHOLD_INKY 30
#define RELEASE_THRESHOLD_CLYDE 90
#endif
