#ifndef MAPTILE_H
#define MAPTILE_H
#define NUMBER_OF_DOTS 244
typedef enum MapTile {
  TILE_WALL,
  TILE_DOT,
  TILE_POWER_PELLET,
  TILE_EMPTY,
  TILE_PLAYER,
  TILE_GHOST_DOOR,
  TILE_FRUIT
} MapTile;
#endif